import { compile } from "../src/engine";
import { makeLink, makeNode } from "../src/engine/sample";
import { sanitizeNetwork } from "../src/engine/validate";
import * as ops from "../src/state/ops";
const W = makeNode(-400, 0), X = makeNode(-150, 8, "priority", false), J = makeNode(0, 0, "lights", false), E = makeNode(400, 10), N = makeNode(0, -250), R = makeNode(700, 10, "roundabout", false), F = makeNode(900, 10);
const a = makeLink(W, X, 1, 1), a2 = makeLink(X, J, 1, 1), b = makeLink(J, E, 1, 1), side = makeLink(N, J, 1, 1), c = makeLink(E, R, 1, 1), d = makeLink(R, F, 1, 1), g = makeLink(R, makeNode(700, 300), 1, 1);
let net = sanitizeNetwork({ version: 1, nodes: [W, X, J, E, N, R, F, g.to === undefined ? W : (null as any)].filter(Boolean), stops: [], lines: [], links: [a, a2, b, side, c, d] });
console.log("chain from b:", ops.straightChain(net, b.id).map(id => [a, a2, b, side, c, d].find(l => l.id === id) === a ? "a" : id === a2.id ? "a2" : id === b.id ? "b" : id === c.id ? "c" : id === d.id ? "d" : "side"));
const [n2, def] = ops.addReversible(net, b.id, true);
const comp = compile(sanitizeNetwork(n2));
console.log("def", def?.name, "start is W", def?.start === W.id, "corridor roads", comp.corridors[0]?.links.length, "warnings", comp.warnings);
const n3 = ops.leaveReversible(n2, a2.id);
console.log("leave middle road refused:", n3 === n2);
const n4 = ops.leaveReversible(n2, a.id);
console.log("leave end road:", compile(sanitizeNetwork(n4)).corridors[0]?.links.length, "start moved to X:", n4.reversibles?.[0].start === X.id);
console.log("extend back:", compile(sanitizeNetwork(ops.extendReversible(n4, def!.id))).corridors[0]?.links.length);
console.log("delete:", ops.deleteReversible(n2, def!.id).links.filter(l => l.rev).length, (ops.deleteReversible(n2, def!.id).reversibles ?? []).length);
